dataset:
  name: bird_grayscale
  folder: C:/Users/Justin/Documents/Github_Work/MetaLearner_V1_main/data/CUB_200_2011/CUB_200_2011

latent_size: 128
random_seed: 42
run_comparisons: False
train_body: True


classifier_training:
  epochs: 200
  batch_size: 64
  loss_fun: CE
  lf_model: resnet
  hf_model: resnet
  trained_lf_model: C:\Users\Justin\Documents\ML_Work\Fidelity_Selection\src\results\bird_grayscale-resnet-resnet-42-128_GOOD\models\lf_model.pt
  trained_hf_model: C:\Users\Justin\Documents\ML_Work\Fidelity_Selection\src\results\bird_grayscale-resnet-resnet-42-128_GOOD\models\hf_model.pt
  
fe_training:
  epochs: 40
  batch_size: 128
  reruns: 1

  r_range:
    start: 0.0
    stop: 1.0
    num_steps: 100
    scale: linear
    direction: reversed # normal: 0 -> 1, reversed 1 -> 0