dataset:
  name: crop
  folder: ../data

latent_size: 128
random_seed: 42
run_comparisons: False
train_body: True

classifier_training:
  epochs: 50
  batch_size: 32
  loss_fun: CE
  lf_model: unet
  hf_model: unet
  
fe_training:
  epochs: 40
  batch_size: 128

  r_range:
    start: 0.0
    stop: 1.0
    num_steps: 100
    scale: linear
    direction: reversed # normal: 0 -> 1, reversed 1 -> 0