dataset:
  name: mnist
  folder: ../data
  augmentations:
    high_fidelity:
      augmentation: none
      strength: 0
      steps: 0
      schedule: linear

    low_fidelity:
      augmentation: noise
      strength: 0.5
      steps: 5
      schedule: decay

parameters:
  latent_representation_size: 64
  random_seed: 42
  num_reruns: 1

stage1:
  epochs: 200
  hf_save_location: ../saved_models/hf_models
  lf_save_location: ../saved_models/lf_models
  results_save_location: ../results/stage1
  batch_size: 16
  loss_fun: CE

  early_stop:
    patience: 7
    min_delta: 1e-4

# Removed classifier information from stage1 and stage2

stage2:
  epochs: 200
  fe_save_location: ../saved_models/fe_models
  results_save_location: ../results/stage2
  batch_size: 4096

  fe_model:
    optimizer:
      lr: 3e-3
      weight_decay: 1e-5

    scheduler:
      gamma: .99

    early_stop:
      patience: 5
      min_delta: 0

  r_range:
    start: 0.0
    stop: 1.0
    num_steps: 100
    scale: linear
    direction: reversed # normal: 0 -> 1, reversed 1 -> 0